chapter_00/src/Main.java

Add: 最初の課題を実施

---

chapter_00/src/Main.java

最初の課題を実施しました。
さらにコードを追加したので確認お願いします。

Add: 最初の課題を実施(コードを追加)

---

.idea/codeStyles/codeStyleConfig.xml
chapter_00/src/Main.java

Develop 645 #1

---

chapter_00/src/Main.java

最初の課題を実施しました。
さらにコードを追加したので確認お願いします。

Add:最初の課題を実施

---

chapter_01/src/domain/service/TaskServiceImplementedBy506.java

Add:#9の課題を実施

---

chapter_00/src/Main.java

Add:最初の課題実施

---

chapter_01/src/Main.java

Fix: Main.javaを誤って消してしまったので再作成

---

chapter_01/src/domain/service/TaskServiceImplementedBy092.java

Add: １章課題実施

---

chapter_02/src/domain/service/TaskServiceImplementedBy617.java

Fix: セミコロン抜けでこけてたのを修正

---

chapter_02/src/domain/service/TaskServiceImplementedBy506.java

Add:#20の課題を実施

---

chapter_02/src/domain/service/TaskServiceImplementedBy617.java

Develop 617 #20 review

---

chapter_03/src/domain/service/TaskServiceImplementedBy617.java

chapter_03の課題を実施しました。
ご確認をお願い致します。

Add:chapter_03の課題を実施しました。

---

chapter_02/src/domain/service/TaskServiceImplementedBy645.java
chapter_03/src/domain/service/TaskServiceImplementedBy645.java

Develop 645 #32

---

chapter_03/src/domain/service/TaskServiceImplementedBy506.java

失礼致しました。
ブランチを間違えておりましたので再度プルリクエスト致します。

Add:#29の課題を実施

---

chapter_04/src/domain/service/TaskServiceImplementedBy617.java

chapter_04の課題を実施しました。
ご確認をお願い致します。

Add:chapter_04の課題を実施

---

chapter_05/src/domain/service/TaskServiceImplementedBy506.java

Add:#53の課題を実施

---

chapter_02/src/domain/service/TaskServiceImplementedBy092.java

Add:chapter_02の課題を実施しました。

---

chapter_04/src/domain/service/TaskServiceImplementedBy092.java

Add:chapter_04の課題を実施しました。

---

chapter_05/src/domain/service/TaskServiceImplementedBy092.java

Add:chapter_05の課題を実施しました。

---

chapter_05/src/domain/service/TaskServiceImplementedBy617.java

chapter_05の課題を実施しました。
ご確認をお願い致します。

Add:chapter_05の課題を実施

---

chapter_06/src/controller/MainController.java
chapter_06/src/domain/service/Human506.java

Add:#76の課題を実施

---

chapter_06/src/controller/MainController.java
chapter_06/src/domain/service/Human617.java

chapter_06の課題を実施しました。
ご確認をお願い致します。

Add:chapter_06の課題を実施

---

chapter_06/src/controller/MainController.java
chapter_06/src/domain/service/Human092.java

Add: ６章課題を実施

---

chapter_07/src/controller/MainController.java
chapter_07/src/domain/service/Boy506.java

Add:#81の課題を実施

---

chapter_07/src/controller/MainController.java
chapter_07/src/domain/service/Girl617.java

第7章の課題を実施しました。
お手数ですが、ご確認をお願い致します。

Develop 617 #81

---

chapter_08/src/controller/MainController.java
chapter_08/src/domain/service/Boy506.java

Add:#114の課題を実施

---

chapter_09/src/controller/MainController.java
chapter_09/src/domain/service/student506/HighSchoolBoy506.java

Add:#115の課題を実施

---

chapter_08/src/Girl617.java
chapter_08/src/controller/MainController.java

課題の実施が遅くなり申し訳ございません。
課題8を実施しました。ご確認をお願い致します。

Add:chapter_08の課題を実施

---

chapter_09/src/controller/MainController.java
chapter_09/src/domain/service/student617/HighSchoolGirl617.java

Add:chapter_09の課題を実施

---

chapter_10/src/controller/MainController.java
chapter_10/src/domain/service/student506/ALife.java
chapter_10/src/domain/service/student506/AnEvent.java
chapter_10/src/domain/service/student506/ILife.java
chapter_10/src/domain/service/student506/ITask.java
chapter_10/src/domain/service/student506/Keeper.java
chapter_10/src/domain/service/student506/Kicker.java
chapter_10/src/domain/service/student506/MyLife.java
chapter_10/src/domain/service/student506/MyTask.java
chapter_10/src/domain/service/student506/Player.java

116の課題を実施しました。
実装に悩んでおりまだ途中ですが、いったんコミットします。
指摘、アドバイスとういただけると助かります。

Add:#116の課題を実施

---

chapter_11/src/domain/service/student506/Task506.java

Add:#143の課題を実施

---

chapter_13/src/domain/service/student506/Task506.java

Add:#155の課題を実施

---

chapter_10/src/controller/MainController.java
chapter_10/src/domain/service/student617/AJob.java
chapter_10/src/domain/service/student617/ATour.java
chapter_10/src/domain/service/student617/ExpediaTour.java
chapter_10/src/domain/service/student617/HisTour.java
chapter_10/src/domain/service/student617/IJob.java
chapter_10/src/domain/service/student617/ITask.java
chapter_10/src/domain/service/student617/JtbTour.java
chapter_10/src/domain/service/student617/MyJob.java
chapter_10/src/domain/service/student617/MyTask.java
chapter_10/src/domain/service/student617/TravelAgency.java

エラーが出ているファイルがありますが一旦コミットしました。
お手数ですが、ご確認をお願い致します。

Add:chapter_10の課題を実施

---

chapter_11/src/domain/service/student617/Task617.java

課題11を実施しました。
お手数ですが、ご確認をお願い致します。

Add:chapter_11の課題を実施

---

chapter_12/src/domain/service/student617/StrongBox.java
chapter_12/src/domain/service/student617/Task617.java

課題１２を実施しました。
お手数ですが、ご確認をお願い致します。

Add:chapter_12の課題を実施

---

chapter_13/src/domain/service/student617/Task617.java

遅くなり大変申し訳ございません。
課題⒔を実施しましたので、ご確認をお願い致します。

Add:chapter_13の課題を実施

---

chapter_12/src/domain/service/student645/AreaCalculation.java
chapter_12/src/domain/service/student645/ExitYutoriSan.java
chapter_12/src/domain/service/student645/Task645.java
chapter_12/src/domain/service/student645/YutoriKun.java
chapter_13/src/domain/service/student645/Task645.java

遅くなり申し訳ございません
こちらがエラーの確認をお願いしたいソースになります。
間違えて前回課題のブランチを更新し、ソースを上げていました。

Devrop 645#155
